api_login_check:
  path: /api/auth/login_check

gesdinet_jwt_refresh_token:
  path:       /api/token/refresh

auth_controllers:
  resource: App\User\Infrastructure\Controller\AuthController
  type: annotation
user_controller:
  resource: App\User\Infrastructure\Controller\UserController
  type: annotation
admin_controller:
  resource: App\User\Infrastructure\Controller\AdminController
  type: annotation

car_controller:
  resource: App\Car\Infrastructure\Controller\CarController
  type: annotation
lessor_car_controller:
  resource: App\Car\Infrastructure\Controller\LessorCarController
  type: annotation
