security:

  password_hashers:
    App\Entity\User: 'auto'
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
      algorithm: 'auto'
      cost: 15

  enable_authenticator_manager: true

  providers:
    user_provider:
      entity:
        class: App\User\Doctrine\Entity\User
        property: email

  firewalls:
    login:
      pattern: ^/api/auth/login
      stateless: true
      json_login:
        check_path: /api/auth/login_check
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    api:
      pattern: ^/api
      stateless: true
      jwt: ~

  access_control:
    - { path: ^/api$,       roles: PUBLIC_ACCESS }
#    - { path: ^/api/login, roles: PUBLIC_ACCESS }
