FROM php:8.1.9-fpm

RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www

RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www

COPY --chown=www:www-data . /var/www

#RUN chown -R www:www-data /var/www/storage
#RUN chmod -R ug+w /var/www/storage

USER www
# Expose port 9000 and start php-fpm server
EXPOSE 9000
CMD ["php-fpm"]