FROM node:18.9-alpine

RUN #npm install -g nodemon

RUN apk add --no-cache bash

RUN deluser --remove-home node \
  && addgroup -S node -g 1000 \
  && adduser -S -G node -u 1000 node

RUN mkdir -p /var/www/ && chown -R node:node /var/www/

USER node

WORKDIR /var/www/
RUN chown -R node:node /var/www

COPY --chown=node:node ../../package*.json ./

RUN npm install

COPY --chown=node:node ../../src/ ./

EXPOSE 3000

CMD ["npm", "run", "start"]